# Generated by Django 5.0.7 on 2024-09-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
